[eproxy]
ip = "127.0.0.1"
port = 12121

[[app]]
name = "app1"
ip = "127.0.0.1"
port = 80
local_ip = "127.0.0.1"
local_port = 10001

[[app]]
name = "app2"
ip = "127.0.0.1"
port = 80
local_ip = "127.0.0.1"
local_port = 10002
